# Generated by Django 2.0.13 on 2020-04-08 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommatefinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='_user_dislikes_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='_user_likes_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='_user_matches_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
