# Generated by Django 2.0.13 on 2020-04-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommatefinder', '0002_auto_20200408_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='matches',
        ),
    ]
