# Generated by Django 2.0.13 on 2020-04-30 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommatefinder', '0005_auto_20200416_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='max_age',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_distance',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='match',
            name='user_one',
            field=models.ManyToManyField(related_name='_match_user_one_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='user_two',
            field=models.ManyToManyField(related_name='_match_user_two_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
