# Generated by Django 2.0.13 on 2020-04-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommatefinder', '0006_auto_20200430_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='_user_matches_+', to='roommatefinder.Match'),
        ),
    ]
