# Generated by Django 2.0.13 on 2020-04-30 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommatefinder', '0007_user_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.CharField(max_length=256)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommatefinder.Match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='messages',
            field=models.ManyToManyField(related_name='_match_messages_+', to='roommatefinder.Message'),
        ),
    ]
